// Generated by CoffeeScript 1.3.3

Spine.Model.prototype.validate = function() {
  var message, validator, _ref, _validator;
  this.errors = [];
  _ref = this.validations;
  for (message in _ref) {
    validator = _ref[message];
    _validator = validator.bind(this);
    if (_validator()) {
      this.errors.push(message);
    }
  }
  return !Spine.isBlank(this.errors);
};
