// Generated by CoffeeScript 1.3.3
var clear, press_enter_key, sum, unique;

unique = function(array) {
  var i, storage, uniqueArray, value;
  storage = {};
  uniqueArray = [];
  i = void 0;
  value = void 0;
  i = 0;
  while (i < array.length) {
    value = array[i];
    if (!(value in storage)) {
      storage[value] = true;
      uniqueArray.push(value);
    }
    i++;
  }
  return uniqueArray;
};

sum = function(array) {
  var total, value, _i, _len;
  total = 0;
  for (_i = 0, _len = array.length; _i < _len; _i++) {
    value = array[_i];
    total += value;
  }
  return total;
};

clear = function(form) {
  form.find('input').each(function() {
    return $(this).val('');
  });
  return $(form.find('input')[0]).focus();
};

press_enter_key = function(event) {
  return event.keyCode === 13;
};
